apiVersion: v1
kind: Service
metadata:
  name: calico-node-metrics-svc
  namespace: kube-system
  labels:
    k8s-app: calico-node
spec:
  clusterIP: None
  selector:
    k8s-app: calico-node
  ports:
  - port: 9091
    name: metrics
    targetPort: 9091
