{{$SetServiceProxyLabel := DefaultParam .SetServiceProxyLabel false}}
{{$includeLabels := or .EnableNetworkPolicyEnforcementLatencyTest (and $SetServiceProxyLabel (eq (Mod .Index 2) 0))}}

apiVersion: v1
kind: Service
metadata:
  name: {{.Name}}
{{if $includeLabels}}
  labels:
{{end}}
{{if and $SetServiceProxyLabel (eq (Mod .Index 2) 0)}}
    service.kubernetes.io/service-proxy-name: foo
{{end}}
{{if .EnableNetworkPolicyEnforcementLatencyTest}}
    {{.TargetLabelKey}}: {{.TargetLabelValue}}
{{end}}
spec:
{{if .HeadlessService}}
  clusterIP: None
{{end}}
  selector:
    svc: {{.Name}}
  ports:
  - port: 80
    targetPort: 80
