{{$PROMETHEUS_SCRAPE_CALICO_NODE := DefaultParam .PROMETHEUS_SCRAPE_CALICO_NODE false}}

{{if $PROMETHEUS_SCRAPE_CALICO_NODE}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: kube-proxy
  name: kube-proxy
  namespace: monitoring
spec:
  endpoints:
    - interval: 5m
      port: metrics
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      k8s-app: kube-proxy
{{end}}
