apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    k8s-app: net-policy-client-pods
  name: net-policy-client-pods
  namespace: monitoring
spec:
  podMetricsEndpoints:
    - interval: 10s
      port: npdelaymetrics
  jobLabel: k8s-app
  selector:
    matchExpressions:
      - {key: test, operator: In, values: [np-client, np-client-podcreation]}
    # matchLabels:
    #   test: np-client
  namespaceSelector:
    any: true
  # namespaceSelector:
  #   matchNames:
  #     - kube-system
