apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    k8s-app: calico-node-pods
  name: calico-node-pods
  namespace: monitoring
spec:
  podMetricsEndpoints:
    - interval: 5m
      # targetPort: 9091
      port: felixmetrics
  jobLabel: k8s-app
  selector:
    matchLabels:
      k8s-app: calico-node
  namespaceSelector:
    matchNames:
      - kube-system
