apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
  labels:
    type: {{.TypeLabel}}
    #test: {{.TestClientLabel}}
spec:
  podSelector:
    matchLabels:
      type: {{.TypeLabel}}
      #test: {{.TestClientLabel}}
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          {{.TargetLabelKey}}: {{.TargetLabelValue}}
      namespaceSelector: {}
