apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Name}}
  labels:
    test: net-policy
spec:
  replicas: {{.NumReplicas}}
  selector:
    matchLabels:
      name: {{.Name}}
  template:
    metadata:
      labels:
        test: net-policy
        name: {{.Name}}
    spec:
      containers:
      - name: {{.Name}}
        image: nginx
        ports:
        - containerPort: 80
