apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: allow-all-control-plane
spec:
  description: A cluster-wide policy to allow all control plane ingress and egress connectivity
  endpointSelector: {}
  egress:
    - toServices:
        - k8sService:
            serviceName: kubernetes
            namespace: default
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
    - toEntities:
        - kube-apiserver
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
    - toCIDRSet:
        - cidr: {{.kubeAPIServerIP}}/32
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
  ingress:
    - fromEntities:
        - kube-apiserver
