{{$serviceAccountName := "np-latency-test"}}
{{$testLabelValue := "np-test-client"}}
{{$targetLabelKey := "group"}}
{{$targetLabelValue := "net-policy-latency"}}

{{$LOAD_TEST_THROUGHPUT := DefaultParam .CL2_LOAD_TEST_THROUGHPUT 100}}
{{$DELETE_TEST_THROUGHPUT := DefaultParam .CL2_DELETE_TEST_THROUGHPUT 30}}

{{$namespaces := DefaultParam .CL2_NAMESPACES 50}}
{{$replicasPerNamespace := DefaultParam .CL2_REPLICAS_PER_NAMESPACE 360}}
{{$PODS_PER_DEP := DefaultParam .CL2_PODS_PER_DEP 1}}
{{$BASE_METRICS_PORT := DefaultParam .CL2_BASE_METRICS_PORT 9154}}

# Baseline test means that it will measure pod connectivity latency without creating network policies.
# This only applies to the measured latency for pod creation, and not for network policy creation.
{{$BASELINE_TEST := DefaultParam .CL_BASELINE_TEST false}}

name: network-policy-latency
namespace:
  number: {{$namespaces}}
tuningSets:
- name: defaultQPS
  qpsLoad:
    qps: {{$LOAD_TEST_THROUGHPUT}}
- name: deleteQPS
  qpsLoad:
    qps: {{$DELETE_TEST_THROUGHPUT}}
steps:

- name: Start Prometheus generic metrics measurements
  measurements:
  - Identifier: GetNetPolicyLatencyMetrics
    Method: GenericPrometheusQuery
    Params:
      action: start
      metricName: Network Policy Enforcement Latency
      metricVersion: v1
      unit: s
      queries:
{{if not $BASELINE_TEST}}
        - name: PolicyCreation - TargetCount
          query: sum(policy_enforcement_latency_policy_creation_seconds_count)#[%v:]
        - name: PolicyCreation - Bucket 3s
          query: sum(policy_enforcement_latency_policy_creation_seconds_bucket{le="1"})#[%v:]
        - name: PolicyCreation - Bucket 5s
          query: sum(policy_enforcement_latency_policy_creation_seconds_bucket{le="3"})#[%v:]
        - name: PolicyCreation - Bucket 10s
          query: sum(policy_enforcement_latency_policy_creation_seconds_bucket{le="5"})#[%v:]
        - name: PolicyCreation - Perc99
          query: histogram_quantile(0.99, sum(rate(policy_enforcement_latency_policy_creation_seconds_bucket[%v])) by (le))
          # threshold: 10
        - name: PolicyCreation - Perc90
          query: histogram_quantile(0.9, sum(rate(policy_enforcement_latency_policy_creation_seconds_bucket[%v])) by (le))
        - name: PolicyCreation - Perc50
          query: histogram_quantile(0.5, sum(rate(policy_enforcement_latency_policy_creation_seconds_bucket[%v])) by (le))
          # threshold: 5
{{end}}
        - name: PodCreation - TargetCount
          query: sum(policy_enforcement_latency_pod_creation_seconds_count)#[%v:]
        - name: PodCreation - Bucket 0.1s
          query: sum(policy_enforcement_latency_pod_creation_seconds_bucket{le="0.1"})#[%v:]
        - name: PodCreation - Bucket 0.5s
          query: sum(policy_enforcement_latency_pod_creation_seconds_bucket{le="0.5"})#[%v:]
        - name: PodCreation - Bucket 1s
          query: sum(policy_enforcement_latency_pod_creation_seconds_bucket{le="1"})#[%v:]
        - name: PodCreation - Bucket 3s
          query: sum(policy_enforcement_latency_pod_creation_seconds_bucket{le="3"})#[%v:]
        - name: PodCreation - Bucket 5s
          query: sum(policy_enforcement_latency_pod_creation_seconds_bucket{le="5"})#[%v:]
        - name: PodCreation - Bucket 10s
          query: sum(policy_enforcement_latency_pod_creation_seconds_bucket{le="10"})#[%v:]
        - name: PodCreation - Bucket 60s
          query: sum(policy_enforcement_latency_pod_creation_seconds_bucket{le="60"})#[%v:]
        - name: PodCreation - Bucket 600s
          query: sum(policy_enforcement_latency_pod_creation_seconds_bucket{le="600"})#[%v:]
        - name: PodCreation - Perc99
          query: histogram_quantile(0.99, sum(rate(policy_enforcement_latency_pod_creation_seconds_bucket[%v])) by (le))
          # threshold: 30
        - name: PodCreation - Perc90
          query: histogram_quantile(0.9, sum(rate(policy_enforcement_latency_pod_creation_seconds_bucket[%v])) by (le))
        - name: PodCreation - Perc50
          query: histogram_quantile(0.5, sum(rate(policy_enforcement_latency_pod_creation_seconds_bucket[%v])) by (le))
          # threshold: 15
        - name: PodIpAssignedLatency - TargetCount
          query: sum(pod_ip_address_assigned_latency_seconds_count)#[%v:]
        - name: PodIpAssignedLatency - Bucket 1s
          query: sum(pod_ip_address_assigned_latency_seconds_bucket{le="1"})#[%v:]
        - name: PodIpAssignedLatency - Bucket 3s
          query: sum(pod_ip_address_assigned_latency_seconds_bucket{le="3"})#[%v:]
        - name: PodIpAssignedLatency - Bucket 5s
          query: sum(pod_ip_address_assigned_latency_seconds_bucket{le="5"})#[%v:]
        - name: PodIpAssignedLatency - Bucket 10s
          query: sum(pod_ip_address_assigned_latency_seconds_bucket{le="10"})#[%v:]
        - name: PodIpAssignedLatency - Bucket 30s
          query: sum(pod_ip_address_assigned_latency_seconds_bucket{le="30"})#[%v:]
        - name: PodIpAssignedLatency - Bucket 60s
          query: sum(pod_ip_address_assigned_latency_seconds_bucket{le="60"})#[%v:]
        - name: PodIpAssignedLatency - Bucket 600s
          query: sum(pod_ip_address_assigned_latency_seconds_bucket{le="600"})#[%v:]
        - name: PodIpAssignedLatency - Perc50
          query: histogram_quantile(0.50, sum(rate(pod_ip_address_assigned_latency_seconds_bucket[%v])) by (le))
        - name: PodIpAssignedLatency - Perc90
          query: histogram_quantile(0.90, sum(rate(pod_ip_address_assigned_latency_seconds_bucket[%v])) by (le))
        - name: PodIpAssignedLatency - Perc99
          query: histogram_quantile(0.99, sum(rate(pod_ip_address_assigned_latency_seconds_bucket[%v])) by (le))
          # threshold: 30
        - name: CEPPropagationDelay - TargetCount
          query: sum(cep_propagation_latency_seconds_count)#[%v:]
        - name: CEPPropagationDelay - Bucket 1s
          query: sum(cep_propagation_latency_seconds_bucket{le="1"})#[%v:]
        - name: CEPPropagationDelay - Bucket 3s
          query: sum(cep_propagation_latency_seconds_bucket{le="3"})#[%v:]
        - name: CEPPropagationDelay - Bucket 5s
          query: sum(cep_propagation_latency_seconds_bucket{le="5"})#[%v:]
        - name: CEPPropagationDelay - Bucket 10s
          query: sum(cep_propagation_latency_seconds_bucket{le="10"})#[%v:]
        - name: CEPPropagationDelay - Bucket 30s
          query: sum(cep_propagation_latency_seconds_bucket{le="30"})#[%v:]
        - name: CEPPropagationDelay - Bucket 60s
          query: sum(cep_propagation_latency_seconds_bucket{le="60"})#[%v:]
        - name: CEPPropagationDelay - Bucket 600s
          query: sum(cep_propagation_latency_seconds_bucket{le="600"})#[%v:]
        - name: CEPPropagationDelay - Perc99
          query: histogram_quantile(0.99, sum(rate(cep_propagation_latency_seconds_bucket[%v])) by (le))
          # threshold: 30
        # - name: PodReadyStateLatency - TargetCount
        #   query: sum(pod_ready_latency_seconds_count)#[%v:]
        # - name: PodReadyStateLatency - Bucket 1s
        #   query: sum(pod_ready_latency_seconds_bucket{le="1"})#[%v:]
        # - name: PodReadyStateLatency - Bucket 3s
        #   query: sum(pod_ready_latency_seconds_bucket{le="3"})#[%v:]
        # - name: PodReadyStateLatency - Bucket 5s
        #   query: sum(pod_ready_latency_seconds_bucket{le="5"})#[%v:]
        # - name: PodReadyStateLatency - Bucket 10s
        #   query: sum(pod_ready_latency_seconds_bucket{le="10"})#[%v:]
        # - name: PodReadyStateLatency - Bucket 30s
        #   query: sum(pod_ready_latency_seconds_bucket{le="30"})#[%v:]
        # - name: PodReadyStateLatency - Bucket 60s
        #   query: sum(pod_ready_latency_seconds_bucket{le="60"})#[%v:]
        # - name: PodReadyStateLatency - Bucket 600s
        #   query: sum(pod_ready_latency_seconds_bucket{le="600"})#[%v:]
        # - name: PodReadyStateLatency - Perc99
        #   query: histogram_quantile(0.99, sum(rate(pod_ready_latency_seconds_bucket[%v])) by (le))
        #   threshold: 30
        # - name: PodScheduledLatency - TargetCount
        #   query: sum(pod_scheduled_latency_seconds_count)#[%v:]
        # - name: PodScheduledLatency - Bucket 1s
        #   query: sum(pod_scheduled_latency_seconds_bucket{le="1"})#[%v:]
        # - name: PodScheduledLatency - Bucket 3s
        #   query: sum(pod_scheduled_latency_seconds_bucket{le="3"})#[%v:]
        # - name: PodScheduledLatency - Bucket 5s
        #   query: sum(pod_scheduled_latency_seconds_bucket{le="5"})#[%v:]
        # - name: PodScheduledLatency - Bucket 10s
        #   query: sum(pod_scheduled_latency_seconds_bucket{le="10"})#[%v:]
        # - name: PodScheduledLatency - Bucket 30s
        #   query: sum(pod_scheduled_latency_seconds_bucket{le="30"})#[%v:]
        # - name: PodScheduledLatency - Bucket 60s
        #   query: sum(pod_scheduled_latency_seconds_bucket{le="60"})#[%v:]
        # - name: PodScheduledLatency - Bucket 600s
        #   query: sum(pod_scheduled_latency_seconds_bucket{le="600"})#[%v:]
        # - name: PodScheduledLatency - Perc99
        #   query: histogram_quantile(0.99, sum(rate(pod_scheduled_latency_seconds_bucket[%v])) by (le))
        #   threshold: 30
        

- name: Wait for test client pods (pod creation) - start measurement
  measurements:
  - Method: WaitForControlledPodsRunning
    Instances:
    - Identifier: WaitForTestClientPods
      Params:
        apiVersion: apps/v1
        kind: Deployment
    Params:
      action: start
      labelSelector: "test = {{$testLabelValue}}"
      operationTimeout: 5m

- name: Setup network policy enforcement latency measurement
  measurements:
  - Identifier: NetworkPolicyEnforcement
    Method: NetworkPolicyEnforcement
    Params:
      action: setup
      targetLabelKey: {{$targetLabelKey}}
      targetLabelValue: {{$targetLabelValue}}
      baseline: {{$BASELINE_TEST}}
      # podCreation: true

- name: Start pod creation network policy enforcement latency measurement
  measurements:
  - Identifier: NetworkPolicyEnforcement
    Method: NetworkPolicyEnforcement
    Params:
      action: create
      podCreation: true
      expectedTargets: 1000
      measureCilium: false # false for Calico, true for Cilium

- name: Wait for test client pods (pod creation) - gather measuerement
  measurements:
  - Method: WaitForControlledPodsRunning
    Instances:
    - Identifier: WaitForTestClientPods
    Params:
      action: gather

- name: Wait for target pods - start measurement
  measurements:
  - Method: WaitForControlledPodsRunning
    Instances:
    - Identifier: WaitForRunningDeployments
      Params:
        apiVersion: apps/v1
        kind: Deployment
    Params:
      action: start
      labelSelector: "{{$targetLabelKey}} = {{$targetLabelValue}}"
      operationTimeout: 15m

- name: Creating deployments
  phases:
  - namespaceRange:
      min: 1
      max: {{$namespaces}}
    replicasPerNamespace: {{$replicasPerNamespace}}
    tuningSet: defaultQPS
    objectBundle:
    - basename: np-dep
      objectTemplatePath: dep.yaml
      templateFillMap:
        NumReplicas: {{$PODS_PER_DEP}}
        TestLabelValue: {{$testLabelValue}}
        TargetLabelKey: {{$targetLabelKey}}
        TargetLabelValue: {{$targetLabelValue}}

- name: Wait for target pods - gather measuerement
  measurements:
  - Method: WaitForControlledPodsRunning
    Instances:
    - Identifier: WaitForRunningDeployments
    Params:
      action: gather

- name: Wait 15min for pods to be reached (Pod creation)
  measurements:
   - Identifier: Wait
     Method: Sleep
     Params:
       duration: 15m

{{if not $BASELINE_TEST}}
- name: Start pod creation network policy enforcement latency measurement
  measurements:
  - Identifier: NetworkPolicyEnforcement
    Method: NetworkPolicyEnforcement
    Params:
      action: create
      # targetLabelKey: {{$targetLabelKey}}
      # targetLabelValue: {{$targetLabelValue}}
      # baseline: {{$BASELINE_TEST}}
      podCreation: false
      expectedTargets: 1000
      # measureCilium: false # false for Calico, true for Cilium

- name: Wait 5min for pods to be reached (Policy creation)
  measurements:
   - Identifier: Wait
     Method: Sleep
     Params:
       duration: 5m
{{end}}

# - name: Gather measurements
#   measurements:
#   - Identifier: GetNetPolicyLatencyMetrics
#     Method: GenericPrometheusQuery
#     Params:
#       action: gather
#       enableViolations: true

- name: Clean up target deployments
  phases:
  - namespaceRange:
      min: 1
      max: {{$namespaces}}
    replicasPerNamespace: 0
    tuningSet: deleteQPS
    objectBundle:
    - basename: np-dep
      objectTemplatePath: dep.yaml

- name: Waiting for resource clean up to be completed for pods
  measurements:
  - Method: WaitForControlledPodsRunning
    Instances:
    - Identifier: WaitForRunningDeployments
    Params:
      action: gather

- name: Setup network policy enforcement latency measurement
  measurements:
  - Identifier: NetworkPolicyEnforcement
    Method: NetworkPolicyEnforcement
    Params:
      action: gather

- name: Gather measurements
  measurements:
  - Identifier: GetNetPolicyLatencyMetrics
    Method: GenericPrometheusQuery
    Params:
      action: gather
      enableViolations: true
