{{$PODS_PER_DEP := DefaultParam .CL2_PODS_PER_DEP 1}}

{{$serviceAaccountName := "np-latency-test"}}
{{$testLabelValue := "np-latency"}}
{{$targetLabelKey := "group"}}
{{$targetLabelValue := "net-policy-latency"}}

{{$qps := 20}}
{{$namespaces := 10}}
{{$replicasPerNamespace := 50}}

name: network-policy-latency
namespace:
  number: {{$namespaces}}
tuningSets:
- name: defaultQPS
  qpsLoad:
    qps: {{$qps}}
steps:

# - name: Create Prometheus pod monitor for network policy test client pods
#   phases:
#   - namespaceRange:
#       min: 1
#       max: 1
#     replicasPerNamespace: 1
#     tuningSet: defaultQPS
#     objectBundle:
#     - basename: np-test-client-pods
#       objectTemplatePath: manifests/prometheus-podMonitorNpClient.yaml

- name: Start measurements
  measurements:
  - Identifier: GetNetPolicyLatencyMetrics
    Method: GenericPrometheusQuery
    Params:
      action: start
      metricName: Network Policy Enforcement Latency
      metricVersion: v1
      unit: ms
      queries:
        - name: TargetCount
          query: sum(policy_enforcement_latency_policy_creation_seconds_count)#[%v:]
        - name: Perc99
          query: histogram_quantile(0.99, sum(rate(policy_enforcement_latency_policy_creation_seconds_bucket[%v])) by (le))
          threshold: 10
        - name: Perc90
          query: histogram_quantile(0.9, sum(rate(policy_enforcement_latency_policy_creation_seconds_bucket[%v])) by (le))
        - name: Perc50
          query: histogram_quantile(0.5, sum(rate(policy_enforcement_latency_policy_creation_seconds_bucket[%v])) by (le))
          threshold: 5

- name: Creating service accounts, roles and rolebindings
  phases:
  - namespaceRange:
      min: 1
      max: {{$namespaces}}
    replicasPerNamespace: 1
    tuningSet: defaultQPS
    objectBundle:
    - basename: {{$serviceAaccountName}}
      objectTemplatePath: manifests/serviceaccount.yaml
    - basename: {{$serviceAaccountName}}
      objectTemplatePath: manifests/role.yaml
    - basename: {{$serviceAaccountName}}
      objectTemplatePath: manifests/rolebinding.yaml

# - name: Creating service accounts, roles and rolebindings
#   phases:
#   - namespaceRange:
#       min: 1
#       max: {{$namespaces}}
#     replicasPerNamespace: 1
#     tuningSet: defaultQPS
#     objectBundle:
#     - basename: {{$serviceAaccountName}}
#       objectTemplatePath: manifests/test-client-permissions.yaml

- name: Creating deny network policies
  phases:
  - namespaceRange:
      min: 1
      max: {{$namespaces}}
    replicasPerNamespace: {{$replicasPerNamespace}}
    tuningSet: defaultQPS
    objectBundle:
    - basename: np-latency-deny
      objectTemplatePath: manifests/policy-deny.yaml
      templateFillMap:
        TargetLabelKey: {{$targetLabelKey}}
        TargetLabelValue: {{$targetLabelValue}}

- name: Wait for target pods - start measurement
  measurements:
  - Method: WaitForControlledPodsRunning
    Instances:
    - Identifier: WaitForRunningDeployments
      Params:
        apiVersion: apps/v1
        kind: Deployment
    Params:
      action: start
      labelSelector: "{{$targetLabelKey}} = {{$targetLabelValue}}"
      operationTimeout: 2m

- name: Creating deployments
  phases:
  - namespaceRange:
      min: 1
      max: {{$namespaces}}
    replicasPerNamespace: {{$replicasPerNamespace}}
    tuningSet: defaultQPS
    objectBundle:
    - basename: np-dep
      objectTemplatePath: dep.yaml
      templateFillMap:
        NumReplicas: {{$PODS_PER_DEP}}
        TestLabelValue: {{$testLabelValue}}
        TargetLabelKey: {{$targetLabelKey}}
        TargetLabelValue: {{$targetLabelValue}}

- name: Wait for target pods - gather measuerement
  measurements:
  - Method: WaitForControlledPodsRunning
    Instances:
    - Identifier: WaitForRunningDeployments
    Params:
      action: gather

- name: Wait for test client pods - start measurement
  measurements:
  - Method: WaitForControlledPodsRunning
    Instances:
    - Identifier: WaitForTestClientPods
      Params:
        apiVersion: apps/v1
        kind: Deployment
    Params:
      action: start
      labelSelector: test = np-client
      operationTimeout: 2m

- name: Creating test client deployments
  phases:
  - namespaceRange:
      min: 1
      max: {{$namespaces}}
    replicasPerNamespace: 1
    tuningSet: defaultQPS
    objectBundle:
    - basename: test-client-dep
      objectTemplatePath: manifests/dep-test-client.yaml
      templateFillMap:
        TargetLabelSelector: "{{$targetLabelKey}} = {{$targetLabelValue}}"
        ServiceAccountName: "{{$serviceAaccountName}}-0"

- name: Wait for test client pods - gather measuerement
  measurements:
  - Method: WaitForControlledPodsRunning
    Instances:
    - Identifier: WaitForTestClientPods
    Params:
      action: gather

- name: Creating allow network policies
  phases:
  - namespaceRange:
      min: 1
      max: {{$namespaces}}
    replicasPerNamespace: {{$replicasPerNamespace}}
    tuningSet: defaultQPS
    objectBundle:
    - basename: np-latency-allow
      objectTemplatePath: manifests/policy-allow.yaml
      templateFillMap:
        TestLabelValue: {{$testLabelValue}}
        TargetLabelKey: {{$targetLabelKey}}
        TargetLabelValue: {{$targetLabelValue}}

- name: Wait 2min for pods to be reached
  measurements:
   - Identifier: Wait
     Method: Sleep
     Params:
       duration: 2m

- name: Clean up deployments and network policies
  phases:
  - namespaceRange:
      min: 1
      max: {{$namespaces}}
    replicasPerNamespace: 0
    tuningSet: defaultQPS
    objectBundle:
    - basename: np-dep
      objectTemplatePath: dep.yaml
    - basename: np-latency-deny
      objectTemplatePath: networkpolicy-deny.yaml
    - basename: np-latency-allow
      objectTemplatePath: networkpolicy-allow.yaml

- name: Clean up test client deployments and permission resources
  phases:
  - namespaceRange:
      min: 1
      max: {{$namespaces}}
    replicasPerNamespace: 0
    tuningSet: defaultQPS
    objectBundle:
    - basename: test-client-dep
      objectTemplatePath: manifests/dep-test-client.yaml
    - basename: np-latency-test
      objectTemplatePath: manifests/test-client-permissions.yaml

- name: Waiting for resource clean up to be completed for pods
  measurements:
  - Method: WaitForControlledPodsRunning
    Instances:
    - Identifier: WaitForRunningDeployments
    - Identifier: WaitForTestClientPods
    Params:
      action: gather

- name: Gather measurements
  measurements:
  - Identifier: GetNetPolicyLatencyMetrics
    Method: GenericPrometheusQuery
    Params:
      action: gather
      enableViolations: true
