apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Name}}
  labels:
    test: np-client
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{.Name}}
  template:
    metadata:
      labels:
        test: np-client
        name: {{.Name}}
    spec:
      containers:
      - name: net-policy-latency-client
        ports:
        - containerPort: 9154
          hostPort: 9154
          name: npdelaymetrics
          protocol: TCP
        imagePullPolicy: Always
        image: gcr.io/gke-networking-test-images/scale-tests/network-policy-latency-client:v0.0.2
        # args:
        #   - -targetLabelSelector "group = net-policy-latency"
        command:
        - sh
        - -c
        - ./network-policy-latency-client -targetLabelSelector "{{.TargetLabelSelector}}" -targetNamespace "{{.Namespace}}" -maxTargets 100
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 150m
            memory: 50Mi
          # limits:
          #   cpu: 70m
          #   memory: 30Mi
          # requests:
          #   cpu: 50m
          #   memory: 20Mi
        # ports:
        # - containerPort: 80
      serviceAccountName: {{.ServiceAccountName}}
