kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{.Name}}
  # namespace: {{.Namespace}}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{.Name}}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{.Name}}
subjects:
  - kind: ServiceAccount
    name: {{.Name}}
    namespace: {{.Namespace}}
roleRef:
  kind: Role
  name: {{.Name}}
  apiGroup: rbac.authorization.k8s.io
