apiVersion: v1
kind: Service
metadata:
  name: perfdash-status
  namespace: perfdash
  labels:
    app: perfdash
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: perfdash
  ports:
  - name: status
    port: 80
    targetPort: status
  type: ClusterIP
